Cs6065_Homework2/Models/ViewModels/UserNotFoundViewModel.cs
#nullable enable

namespace Cs6065_Homework2.Models.ViewModels
{
    public class UserNotFoundViewModel
    {
        public string? ViewDataTitle { get; set; }
        public string Username { get; set; } = "";
    }
}

Cs6065_Homework2/Controllers/RosterController.cs
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

using Cs6065_Homework2.Models;
using Cs6065_Homework2.Models.ViewModels;
using Cs6065_Homework2.Services;

namespace Cs6065_Homework2.Controllers
{
    public class RosterController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RosterService _rosterService;
        private readonly NflPlayerService _nflPlayerService;

        public RosterController(UserManager<ApplicationUser> userManager,
            RosterService rosterService,
            NflPlayerService nflPlayerService)
        {
            _userManager = userManager;
            _rosterService = rosterService;
            _nflPlayerService = nflPlayerService;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null)
            {
                return Challenge();
            }
            FantasyRoster? roster = await _rosterService.GetRosterForUserIdAsync(currentUser.Id);
            if (roster == null)
            {
                return RedirectToAction("Build");
            }
            return View($"~/Views/{RouteData.Values["controller"]}/ViewRoster.cshtml", roster);
        }

        [Route("Roster/{username}")]
        public async Task<IActionResult> Index(string username)
        {
            ApplicationUser? queriedUser = null;
            try
            {
                queriedUser = await _userManager.Users
                    .Where(user => user.UserName == username)
                    .SingleAsync();
            }
            catch { }
            // queried user not found; return error
            if (queriedUser == null)
            {
                return View("~/Views/Shared/UserNotFound.cshtml", new UserNotFoundViewModel
                    {
                        ViewDataTitle = "Fantasy Roster",
                        Username = username
                    });
            }
            // queried user found: get roster & display
            FantasyRoster? roster = await _rosterService.GetRosterForUserIdAsync(queriedUser.Id);
            return View("~/Views/Roster/ViewRoster.cshtml", roster);
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Build()
        {
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null)
            {
                return Challenge();
            }
            
            var qbs = await _nflPlayerService.GetQuarterbacks().ToListAsync();
            var rbs = await _nflPlayerService.GetRunningBacks().ToListAsync();
            var tes = await _nflPlayerService.GetTightEnds().ToListAsync();
            var wrs = await _nflPlayerService.GetWideReceivers().ToListAsync();

            var viewModel = new BuildFantasyRosterViewModel
                {
                    Quarterbacks = qbs,
                    RunningBacks = rbs,
                    TightEnds = tes,
                    WideReceivers = wrs
                };
            return View(viewModel);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Build(BuildFantasyRosterViewModel model)
        {
            // TODO: this method has some awful repeated code, rebuilding the
            // viewmodel in the error condition which hits the database a "lot".
            // i don't yet know if it can be improved.

            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null)
            {
                return Challenge();
            }
            if (model.RunningBack1Id == model.RunningBack2Id)
            {
                ModelState.AddModelError(String.Empty, "You can't have two of the same running backs.");
            }
            if (model.WideReceiver1Id == model.WideReceiver2Id)
            {
                ModelState.AddModelError(String.Empty, "You can't have two of the same wide receivers.");
            }
            if (ModelState.ErrorCount != 0)
            {
                model.Quarterbacks = await _nflPlayerService.GetQuarterbacks().ToListAsync();
                model.RunningBacks = await _nflPlayerService.GetRunningBacks().ToListAsync();
                model.TightEnds = await _nflPlayerService.GetTightEnds().ToListAsync();
                model.WideReceivers = await _nflPlayerService.GetWideReceivers().ToListAsync();
                return View(model);
            }

            var qb = await _nflPlayerService.GetQuarterbackByIdAsync(model.QuarterbackId);
            var rb1 = await _nflPlayerService.GetRunningBackByIdAsync(model.RunningBack1Id);
            var rb2 = await _nflPlayerService.GetRunningBackByIdAsync(model.RunningBack2Id);
            var te = await _nflPlayerService.GetTightEndByIdAsync(model.TightEndId);
            var wr1 = await _nflPlayerService.GetWideReceiverByIdAsync(model.WideReceiver1Id);
            var wr2 = await _nflPlayerService.GetWideReceiverByIdAsync(model.WideReceiver2Id);

            if (qb == null || rb1 == null || rb2 == null || te == null || wr1 == null || wr2 == null)
            {
                ModelState.AddModelError(String.Empty, "there was an error with one or more submitted player ids.");
                model.Quarterbacks = await _nflPlayerService.GetQuarterbacks().ToListAsync();
                model.RunningBacks = await _nflPlayerService.GetRunningBacks().ToListAsync();
                model.TightEnds = await _nflPlayerService.GetTightEnds().ToListAsync();
                model.WideReceivers = await _nflPlayerService.GetWideReceivers().ToListAsync();
                return View(model);
            }

            FantasyRoster roster = new FantasyRoster
                {
                    Owner = currentUser,
                    OwnerId = currentUser.Id,
                    QuarterbackId = model.QuarterbackId,
                    Quarterback = qb,
                    RunningBack1Id = model.RunningBack1Id,
                    RunningBack1 = rb1,
                    RunningBack2Id = model.RunningBack2Id,
                    RunningBack2 = rb2,
                    TightEndId = model.TightEndId,
                    TightEnd = te,
                    WideReceiver1Id = model.WideReceiver1Id,
                    WideReceiver1 = wr1,
                    WideReceiver2Id = model.WideReceiver2Id,
                    WideReceiver2 = wr2
                };
            
            bool success = await _rosterService.AddOrUpdateRosterAsync(roster);

            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete()
        {
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null)
            {
                return Challenge();
            }
            var result = await _rosterService.DeleteRosterForUserIdAsync(currentUser.Id);
            if (result == true)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index"); // either way we'll go to index v0v
        }
    }
}

Cs6065_Homework2/Views/Shared/UserNotFound.cshtml
@using Cs6065_Homework2.Models.ViewModels

@model UserNotFoundViewModel

@{
    @if (Model.ViewDataTitle != null)
    {
        ViewData["Title"] = Model.ViewDataTitle;
    }
}

<h1>@ViewData["Title"]</h1>
<div class="text-center">
    <h1 class="display-4">error</h1>
    <p>user not found: @Model.Username</p>
</div>

Cs6065_Homework2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cs6065_Homework2</title>
    
    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="~/lib/w2ui/w2ui-1.5.rc1.min.js"></script>
    
    <link rel="stylesheet" type="text/css" href="~/lib/w2ui/w2ui-1.5.rc1.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cs6065_Homework2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Scoreboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Roster" asp-action="Index">Roster</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Player" asp-action="Index">Players</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Cs6065_Homework2 @* - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
        </div>
    </footer>
    
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>